#ifndef DEFAULT_TITRATION_PROGRAM_H
#define DEFAULT_TITRATION_PROGRAM_H

#include "titration_program.h"

// AUTO-GENERATED by experiments/titration_program_embed/gen.py — do not edit by hand.
// Source: khpro.local /api/diagnostics, device fw_build "Jun 10 2026 18:10:18", ts=1781206788.
// Device config at capture: cal_units=15000, titration_vol=11.59,
//   fast_ph=5.0, drop_ul=25.0, fast_step_ul=800.
//
// A real measurement run embedded as the DEFAULT replay program for titration-pump
// calibration. Used only until the first recorded measurement overwrites
// /history/last_titration.prog. 95 steps, total 14731 units (~11.38 mL).
static const TitrationStep DEFAULT_TITRATION_PROGRAM[] = {{1035,0,500},{1034,0,500},{1035,0,500},{1035,0,500},{1035,0,500},{1034,0,500},{1035,0,500},{1035,0,500},{692,0,698},{492,0,814},{282,0,936},{233,0,964},{113,0,1034},{102,0,1040},{104,0,1039},{104,0,1039},{102,0,1040},{104,0,1039},{102,0,1040},{104,0,1039},{102,0,1040},{104,0,1039},{104,0,1039},{102,0,1040},{104,0,1039},{102,0,1040},{104,0,1039},{104,0,1039},{102,0,1040},{104,0,1039},{102,0,1040},{44,2,10168},{52,0,1069},{52,0,1069},{43,2,5168},{43,2,5168},{44,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{44,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{44,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{44,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{44,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{44,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{44,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{44,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{44,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{44,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{44,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{44,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{44,2,5168},{43,2,5168},{43,2,5168},{43,2,5168},{44,2,5168}};
static const int DEFAULT_TITRATION_PROGRAM_LEN =
    sizeof(DEFAULT_TITRATION_PROGRAM) / sizeof(DEFAULT_TITRATION_PROGRAM[0]);

#endif // DEFAULT_TITRATION_PROGRAM_H
